### PR TITLE
:fr: updated

### PR DESCRIPTION
**Pull request by MATsxm**

### CODE REVIEW

**Comment by vistiyos** [comment]
@MATsxm thanks, but would you mind to make the pull request to the stagging brach?

**Comment by MATsxm** [comment]
@vistiyos  Sorry
it seems you did it already?

**Comment by vistiyos** [comment]
Yes, it does not matter now, but for the future would great to merge into staging instead into master, because we work with staging branch.

**Comment by MATsxm** [comment]
Sorry, I missed it

**Pull request merged**
