### PR TITLE
Update fr-FR.com_neno.ini

### PR DESCRIPTION
**Pull request by MAT978**
Bonjour,
line 117 added/translated
409/416 added will be translated LATER this week.
Thanks

### CODE REVIEW

**Comment by vistiyos** [comment]
@MAT978 awesome work as usual. I will wait till you finish the job.

**Comment by MAT978** [comment]
not sure on how to edit my own PR before it's commited but I try... ;)

**Comment by vistiyos** [comment]
@MAT978 Just commit to the same branch you did to open the PR

**Comment by MAT978** [comment]
@vistiyos 

Should be ok now...
thanks ;)

**Pull request merged**
