### PR TITLE
String translations to Spanish & correction in English

### PR DESCRIPTION
**Pull request by andresmaeso**

### CODE REVIEW

**Comment by vistiyos** [comment]
Pull request merged

**Comment by MAT978** [comment]
Hello,
Maybe I'm wrong but I think @andresmaeso worked on an old version of en-GB.
then @vistiyos merged correction of an old version.
(hard to explain ;) )

For example, for my last PR (10 days ago) there was 406 strings to translate then now we get back to 383?
+ for example line 305 was previously correcting see: https://github.com/Jensen-Technologies/neno/pull/74/files and we have now the same previous Typo?

I really do think PR #105 (for en-GB) is based on an old file and not the one should be the current one then not merged.

**Comment by vistiyos** [comment]
@MAT978 OK, I think you are right, let me fix this issue.

**Comment by vistiyos** [comment]
@MAT978 I have fixed this issue.

**Comment by MAT978** [comment]
:+1:

**Pull request merged**
